<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title><?php echo $this->title ?></title>
    <meta NAME="DESCRIPTION" CONTENT="<?php echo $this->metaDescription ?>">
    <meta NAME="KEYWORDS" CONTENT="<?php echo $this->metaKeywords ?>">
    <?php if ($this->nofollow): ?>
    	<meta name="robots" content="nofollow" />
    <?php endif; ?>
    <link rel="stylesheet" type="text/css" href="/assets/css/main.css"/>
</head>
