<br />
<h3>Intent</h3>
<p>
An Interesting demonstration of democracy that Agile teams often do in order to come to a consensus.
</p>
<h3>How is this done:</h3>
<p>
When conclusions have to be done the team is asked to do a fist of five. All the team members put out thier fingers ( five ) . They can show from 1 to five fingers as shown above
</p>
<h3>What does this mean</h3>
<p>
<ul>
<li>1 means you dont agree</li>

<li>3 means you are not sure but you will go with the team</li>

<li>5 means you strongly agree</li>
</ul>
</p>
<p>
Even if one person is below 3 , the decision does not go through. A discussion / debate happens . If you can convince a person less than 3 to come up to a 3, then the decision goes through
</p>